jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.11.0
        with:
          version: 'latest'  # Or specify a specific version

      - name: Authenticate
        run: echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-
      
      - name: Deploy to App Engine
        run: gcloud app deploy
