name: Create GCP Bucket

on:
  push:
    branches:
      - main

jobs:
  create-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode and activate service account
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ${HOME}/gcloud-key.json
        echo "Contents of gcloud-key.json:"
        cat ${HOME}/gcloud-key.json  # Debugging step
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json

    - name: Create GCP Bucket
      run: |
        python create_bucket.py  # Ensure you have your script in the right path
