name: Create GCP Bucket

on:
  push:
    branches:
      - main

jobs:
  create-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Decode and authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > ${HOME}/gcloud-key.json
        cat ${HOME}/gcloud-key.json  # Debugging step to ensure file content
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Create GCP Bucket
      run: |
        gsutil mb -p ${{ secrets.GCP_PROJECT_ID }} gs://sample-github/
