name: Create GCP Bucket

on:
  push:
    branches:
      - main

jobs:
  create-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use the Python version required for your script

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage

    - name: Run Python script to create GCP Bucket
      run: |
        python path/to/your/script.py  # Update with the correct path to your script
