jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.11.0
        with:
          version: 'latest'  # Or specify a specific version

      - name: Authenticate
        run: echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-
      
      - name: Deploy to App Engine
        run: gcloud app deploy
        
name: Create GCP Bucket

on:
  push:
    branches:
      - main

jobs:
  create-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Create GCP Bucket
      run: |
        gsutil mb -p ${{ secrets.GCP_PROJECT_ID }} gs://sample-github/
